package net.java21.crowfoot.api.model.service;

import net.java21.crowfoot.api.model.domain.Model;
import net.java21.crowfoot.api.model.dto.ModelDdlResponse;
import net.java21.crowfoot.api.model.repository.ModelRepository;
import net.java21.crowfoot.api.workspace.service.RoleChecker;
import net.java21.crowfoot.common.error.BusinessException;
import net.java21.crowfoot.common.error.ErrorCode;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import tools.jackson.databind.ObjectMapper;

import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.BDDMockito.given;

/**
 * DDL 생성 서비스 (08-core/02-model.md Section 1.7) — 권한·모델 로드·방언 파생·경고 전달.
 * ObjectMapper는 실물 — content 해석 자체가 테스트 대상이다.
 */
@ExtendWith(MockitoExtension.class)
class DdlServiceTest {

    private static final String CONTENT = """
            {"schemaVersion":1,"model":{
              "tables":[
                {"id":"t1","physicalName":"member",
                 "columns":[
                   {"id":"c1","physicalName":"id","dataType":"BIGINT","nullable":false,"autoIncrement":true},
                   {"id":"c2","physicalName":"active","dataType":"BOOLEAN","nullable":false}],
                 "primaryKey":{"name":"pk_member","columnIds":["c1"]},
                 "uniques":[],"indexes":[]}
              ],
              "relationships":[]}}
            """;

    @Mock
    private ModelRepository modelRepository;
    @Mock
    private RoleChecker roleChecker;

    private DdlService ddlService;

    @BeforeEach
    void setUp() {
        ddlService = new DdlService(modelRepository, roleChecker, new ObjectMapper());
    }

    private Model model(String databaseType, String content) {
        Model model = new Model(77L, "주문 서비스 ERD", null, databaseType, content, 7L);
        model.setId(501L);
        return model;
    }

    @Test
    @DisplayName("postgresql 모델 — 템플릿 파생 방언으로 생성하고 개수를 함께 응답한다")
    void generatesForPostgresql() {
        given(modelRepository.findByIdAndWorkspaceId(501L, 77L))
                .willReturn(Optional.of(model("postgresql", CONTENT)));

        ModelDdlResponse response = ddlService.generate(7L, 77L, 501L);

        assertThat(response.sql())
                .startsWith("-- 주문 서비스 ERD — PostgreSQL DDL")
                .contains("    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY")
                .contains("CONSTRAINT pk_member PRIMARY KEY (id)");
        assertThat(response.warnings()).isEmpty();
        assertThat(response.tableCount()).isEqualTo(1);
        assertThat(response.relationshipCount()).isZero();
    }

    @Test
    @DisplayName("미등록 databaseType 코드는 공용 방언 + COMMON_DIALECT 경고")
    void commonFallbackWarns() {
        given(modelRepository.findByIdAndWorkspaceId(501L, 77L))
                .willReturn(Optional.of(model("mariadb", CONTENT)));

        ModelDdlResponse response = ddlService.generate(7L, 77L, 501L);

        assertThat(response.sql())
                .contains("    active BOOLEAN NOT NULL")
                .doesNotContain("TINYINT(1)");
        assertThat(response.warnings()).singleElement()
                .satisfies(w -> {
                    assertThat(w.code()).isEqualTo("COMMON_DIALECT");
                    assertThat(w.message()).contains("공용(논리)");
                });
    }

    @Test
    @DisplayName("모델이 없으면 MODEL_NOT_FOUND")
    void modelNotFound() {
        given(modelRepository.findByIdAndWorkspaceId(501L, 77L)).willReturn(Optional.empty());

        assertThatThrownBy(() -> ddlService.generate(7L, 77L, 501L))
                .isInstanceOfSatisfying(BusinessException.class,
                        e -> assertThat(e.getErrorCode()).isEqualTo(ErrorCode.MODEL_NOT_FOUND));
    }

    @Test
    @DisplayName("content가 JSON이 아니면 방어 오류 INVALID_REQUEST")
    void malformedContent() {
        given(modelRepository.findByIdAndWorkspaceId(501L, 77L))
                .willReturn(Optional.of(model("postgresql", "not-json")));

        assertThatThrownBy(() -> ddlService.generate(7L, 77L, 501L))
                .isInstanceOfSatisfying(BusinessException.class,
                        e -> assertThat(e.getErrorCode()).isEqualTo(ErrorCode.INVALID_REQUEST));
    }
}
