-- 커뮤니티 신고 44·45(v1.37)의 구조 — 특수 인덱스·CHECK 연산자·IDENTITY 종류·빈 문자열 기본값
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE member (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nickname varchar(30) NOT NULL,
  handle varchar(30) NOT NULL,
  deleted_at timestamp,
  CONSTRAINT ck_member_handle CHECK (handle !~ '^(go|gi)_'),
  CONSTRAINT ck_member_handle_ci CHECK (handle !~* '^admin')
);
CREATE UNIQUE INDEX uq_member_nickname ON member (lower(nickname));
CREATE INDEX ix_member_handle_pattern ON member (handle varchar_pattern_ops);
CREATE INDEX ix_member_active ON member (id) WHERE deleted_at IS NULL;

CREATE TABLE post (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id bigint NOT NULL,
  title varchar(200) NOT NULL DEFAULT '',
  content_md text NOT NULL DEFAULT '',
  view_count int NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_post_author FOREIGN KEY (author_id) REFERENCES member (id)
);
CREATE INDEX ix_post_title_trgm ON post USING gin (title gin_trgm_ops);
CREATE INDEX ix_post_author_recent ON post (author_id, created_at DESC) INCLUDE (title);

CREATE TABLE image (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  owner_id bigint NOT NULL,
  purpose varchar(20) NOT NULL,
  is_current boolean NOT NULL DEFAULT true
);
CREATE UNIQUE INDEX uq_image_profile_current ON image (owner_id) WHERE purpose = 'PROFILE' AND is_current;
