package net.java21.crowfoot.api.model.ddl;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;

/**
 * 방언 레지스트리 — 신규 DBMS는 여기에 구현을 추가한다.
 *
 * <p>자동 증가는 템플릿의 실현 방식과 무관하게 IDENTITY 계열로 통일한다
 * (MySQL AUTO_INCREMENT / MSSQL IDENTITY(1,1) / PG·Oracle GENERATED BY DEFAULT AS IDENTITY —
 * PG 10+·Oracle 12c+ 기준). Oracle 11g 시퀀스+트리거 방식은 후보로 남긴다.
 */
public final class Dialects {

    private Dialects() {
    }

    public static SqlDialect byId(String id) {
        SqlDialect dialect = REGISTRY.get(id);
        return dialect == null ? REGISTRY.get("common") : dialect;
    }

    private static final Map<String, SqlDialect> REGISTRY = Map.of(
            "mysql", new MysqlDialect(),
            "postgres", new PostgresDialect(),
            "oracle", new OracleDialect(),
            "mssql", new MssqlDialect(),
            "common", new CommonDialect());

    /* ---------- 공통 조립 — 모든 방언이 같은 규칙으로 시작하고 차이 지점만 덮어쓴다 ---------- */

    private abstract static class BaseDialect implements SqlDialect {

        private final String id;

        private BaseDialect(String id) {
            this.id = id;
        }

        @Override
        public final String id() {
            return id;
        }

        @Override
        public String columnType(DdlContent.Column column) {
            return DbmsTemplates.assembleType(column, id);
        }

        @Override
        public String autoIncrementInline(DdlContent.Column column) {
            return null;
        }

        @Override
        public String columnComment(DdlContent.Column column) {
            return "";
        }

        @Override
        public String createTablePrefix(DdlContent.Table table) {
            return null;
        }

        @Override
        public String tableOption(DdlContent.Table table) {
            return "";
        }

        @Override
        public List<String> commentStatements(DdlContent.Table table) {
            return List.of();
        }

        /** 이 방언이 받는 인덱스 종류 — 기본은 BTREE만(FULLTEXT·SPATIAL·HASH는 MySQL, GIN 등은 PostgreSQL) */
        protected Set<String> indexTypes() {
            return Set.of(DdlContent.Index.BTREE);
        }

        /** 식 키({@code lower(name)}) — PostgreSQL·Oracle·MySQL 8 */
        protected boolean indexExpression() {
            return false;
        }

        /** 부분 인덱스 조건(WHERE) — PostgreSQL·SQL Server */
        protected boolean indexWhere() {
            return false;
        }

        /** INCLUDE 컬럼 — PostgreSQL·SQL Server */
        protected boolean indexInclude() {
            return false;
        }

        /** 연산자 클래스 — PostgreSQL */
        protected boolean indexOpclass() {
            return false;
        }

        @Override
        public String unsupportedIndexReason(DdlContent.Index index) {
            String type = index.type() == null ? DdlContent.Index.BTREE : index.type();
            if (!indexTypes().contains(type)) {
                return type;
            }
            if (index.expression() != null && !indexExpression()) {
                return "EXPRESSION";
            }
            // 유니크 인덱스에서 조건을 빼면 제약의 뜻이 바뀐다(부분 유니크 → 전체 유니크) — 인덱스째 뺀다
            if (index.unique() && index.where() != null && !indexWhere()) {
                return "UNIQUE WHERE";
            }
            return null;
        }

        @Override
        public List<String> droppedIndexParts(DdlContent.Index index) {
            if (unsupportedIndexReason(index) != null) {
                return List.of();
            }
            List<String> parts = new ArrayList<>();
            if (index.where() != null && !indexWhere()) {
                parts.add("WHERE");
            }
            if (!index.includeColumnIds().isEmpty() && !indexInclude()) {
                parts.add("INCLUDE");
            }
            if (!indexOpclass() && index.columns().stream().anyMatch(column -> column.opclass() != null)) {
                parts.add("opclass");
            }
            return parts;
        }

        /** 이 방언이 표현하지 못하는 인덱스는 null — 생성기가 경고한다. 표현하지 못하는 부분(조건·INCLUDE·연산자 클래스)은
         *  빼고 내며 생성기가 droppedIndexParts로 경고한다 */
        @Override
        public String createIndex(DdlContent.Table table, DdlContent.Index index) {
            if (unsupportedIndexReason(index) != null) {
                return null;
            }
            StringBuilder statement = new StringBuilder("CREATE ");
            if (index.unique()) {
                statement.append("UNIQUE ");
            }
            statement.append(indexKeyword(index)).append(' ').append(index.name())
                    .append(" ON ").append(table.physicalName()).append(indexMethodBeforeKeys(index))
                    .append(" (").append(index.expression() != null ? indexExpressionKeys(index.expression())
                            : indexColumns(table, index, index.btree(), indexOpclass())).append(')');
            if (indexInclude() && !index.includeColumnIds().isEmpty()) {
                List<String> include = new ArrayList<>();
                for (String columnId : index.includeColumnIds()) {
                    DdlContent.Column column = columnById(table, columnId);
                    if (column != null) {
                        include.add(column.physicalName());
                    }
                }
                if (!include.isEmpty()) {
                    statement.append(" INCLUDE (").append(String.join(", ", include)).append(')');
                }
            }
            if (indexWhere() && index.where() != null) {
                statement.append(" WHERE ").append(index.where());
            }
            return statement.append(indexSuffix(index)).toString();
        }

        /** {@code INDEX} 앞 수식 — MySQL은 FULLTEXT·SPATIAL을 붙인다 */
        protected String indexKeyword(DdlContent.Index index) {
            return "INDEX";
        }

        /** 키 목록 앞의 접근 방법 — PostgreSQL {@code USING gin} */
        protected String indexMethodBeforeKeys(DdlContent.Index index) {
            return "";
        }

        /** 문장 끝 — MySQL {@code USING HASH}·{@code WITH PARSER} */
        protected String indexSuffix(DdlContent.Index index) {
            return "";
        }

        /** 식 키 목록 — 원문 그대로. MySQL은 식 조각마다 괄호를 씌운다 */
        protected String indexExpressionKeys(String expression) {
            return expression;
        }

        /** 표준형 — {@code GENERATED ALWAYS AS (식) STORED|VIRTUAL} (MySQL·PostgreSQL) */
        @Override
        public String generatedColumnDefinition(DdlContent.Column column) {
            StringBuilder definition = new StringBuilder(column.physicalName())
                    .append(' ').append(columnType(column))
                    .append(" GENERATED ALWAYS AS (").append(column.generated().expression()).append(") ")
                    .append(generatedStorage(column));
            if (!column.nullable()) {
                definition.append(" NOT NULL");
            }
            return definition.toString();
        }

        /** 저장 방식 키워드 — 방언이 한쪽만 지원하면 덮어쓴다 */
        protected String generatedStorage(DdlContent.Column column) {
            return column.generated().stored() ? "STORED" : "VIRTUAL";
        }

        @Override
        public String onUpdateClause(DdlContent.Column column) {
            return null;
        }

        /* ---------- 마이그레이션 ALTER — ANSI 기본형. 방언이 문법 차이만 덮어쓴다 ---------- */

        @Override
        public String addColumn(DdlContent.Table table, DdlContent.Column column) {
            return "ALTER TABLE " + table.physicalName() + " ADD COLUMN "
                    + DdlGenerator.columnAttributes(column, this) + ";";
        }

        @Override
        public String alterColumn(DdlContent.Table table, DdlContent.Column before, DdlContent.Column after) {
            // 기본형은 타입+NULL 허용 여부만 — 기본값 변경은 방언마다 문법이 갈라져 각자 덮어쓴다
            StringBuilder statement = new StringBuilder("ALTER TABLE ").append(table.physicalName())
                    .append(" ALTER COLUMN ").append(after.physicalName())
                    .append(' ').append(columnType(after));
            if (!after.nullable()) {
                statement.append(" NOT NULL");
            }
            return statement.append(";").toString();
        }

        @Override
        public String dropColumn(DdlContent.Table table, DdlContent.Column column) {
            return "ALTER TABLE " + table.physicalName() + " DROP COLUMN " + column.physicalName() + ";";
        }

        /** 표준형 — PostgreSQL·Oracle. MySQL·SQL Server는 덮어쓴다 */
        @Override
        public String renameTable(String from, String to) {
            return "ALTER TABLE " + from + " RENAME TO " + to + ";";
        }

        /** 표준형 — MySQL 8·PostgreSQL·Oracle이 같은 문법이다 */
        @Override
        public String renameColumn(String table, String from, String to) {
            return "ALTER TABLE " + table + " RENAME COLUMN " + from + " TO " + to + ";";
        }

        @Override
        public String dropConstraint(DdlContent.Table table, String name, String kind) {
            return "ALTER TABLE " + table.physicalName() + " DROP CONSTRAINT " + name + ";";
        }

        @Override
        public String dropIndex(DdlContent.Table table, DdlContent.Index index) {
            return "DROP INDEX " + index.name() + ";";
        }

        @Override
        public List<String> commentRefresh(DdlContent.Table table, DdlContent.Column column) {
            // 코멘트가 줄 주석으로만 존재하는 방언은 CREATE 본문 외에 갱신할 곳이 없다
            return List.of();
        }
    }

    /* ---------- 방언별 차이 지점 ---------- */

    private static final class MysqlDialect extends BaseDialect {

        private MysqlDialect() {
            super("mysql");
        }

        @Override
        public String autoIncrementInline(DdlContent.Column column) {
            return column.autoIncrement() ? "AUTO_INCREMENT" : null;
        }

        @Override
        public String onUpdateClause(DdlContent.Column column) {
            return column.onUpdate() == null ? null : "ON UPDATE " + column.onUpdate();
        }

        @Override
        public String renameTable(String from, String to) {
            return "RENAME TABLE " + from + " TO " + to + ";";
        }

        @Override
        protected Set<String> indexTypes() {
            return Set.of(DdlContent.Index.BTREE, DdlContent.Index.FULLTEXT, DdlContent.Index.SPATIAL, DdlContent.Index.HASH);
        }

        /** 함수 키 조각(8.0.13+) — 조각마다 괄호로 감싼다 */
        @Override
        protected boolean indexExpression() {
            return true;
        }

        /** FULLTEXT·SPATIAL — 컬럼 정렬을 받지 않는다(btree가 아니면 정렬을 빼는 공통 규칙) */
        @Override
        protected String indexKeyword(DdlContent.Index index) {
            return DdlContent.Index.FULLTEXT.equals(index.type()) || DdlContent.Index.SPATIAL.equals(index.type())
                    ? index.type() + " INDEX" : "INDEX";
        }

        /** 전문 검색 파서는 FULLTEXT에만, HASH는 {@code USING HASH}(MEMORY·NDB 엔진만 실제로 따른다) */
        @Override
        protected String indexSuffix(DdlContent.Index index) {
            if (DdlContent.Index.FULLTEXT.equals(index.type()) && index.parser() != null) {
                return " WITH PARSER " + index.parser();
            }
            return DdlContent.Index.HASH.equals(index.type()) ? " USING HASH" : "";
        }

        @Override
        protected String indexExpressionKeys(String expression) {
            List<String> parts = new ArrayList<>();
            for (String part : splitTopLevel(expression)) {
                String trimmed = part.trim();
                // 컬럼 이름(정렬 포함)은 그대로, 식은 괄호로 — MySQL은 식 키 조각을 괄호로 감싸야 한다
                parts.add(SIMPLE_KEY.matcher(trimmed).matches() || (trimmed.startsWith("(") && trimmed.endsWith(")"))
                        ? trimmed : "(" + trimmed + ")");
            }
            return String.join(", ", parts);
        }

        @Override
        public String columnComment(DdlContent.Column column) {
            return column.logicalName() == null ? "" : "COMMENT " + stringLiteral(column.logicalName());
        }

        @Override
        public String tableOption(DdlContent.Table table) {
            return table.logicalName() == null ? "" : " COMMENT=" + stringLiteral(table.logicalName());
        }

        @Override
        public String addColumn(DdlContent.Table table, DdlContent.Column column) {
            // 코멘트는 컬럼 정의에 인라인 — 추가 시점에 함께 심는다
            return "ALTER TABLE " + table.physicalName() + " ADD COLUMN "
                    + withComment(DdlGenerator.columnAttributes(column, this), columnComment(column)) + ";";
        }

        @Override
        public String alterColumn(DdlContent.Table table, DdlContent.Column before, DdlContent.Column after) {
            // MODIFY는 전체 재정의다 — 생략한 속성·코멘트가 사라지므로 after 정의를 전부 다시 쓴다
            return "ALTER TABLE " + table.physicalName() + " MODIFY COLUMN "
                    + withComment(DdlGenerator.columnAttributes(after, this), columnComment(after)) + ";";
        }

        @Override
        public String dropConstraint(DdlContent.Table table, String name, String kind) {
            // UK는 인덱스로, PK는 이름 없는 상수 제약으로 실현된다 — 이름 문법이 각자 다르다
            String target = switch (kind == null ? "" : kind) {
                case KIND_PRIMARY -> "PRIMARY KEY";
                case KIND_UNIQUE -> "INDEX " + name;
                case KIND_FOREIGN_KEY -> "FOREIGN KEY " + name;
                default -> "CONSTRAINT " + name;
            };
            return "ALTER TABLE " + table.physicalName() + " DROP " + target + ";";
        }

        @Override
        public String dropIndex(DdlContent.Table table, DdlContent.Index index) {
            return "DROP INDEX " + index.name() + " ON " + table.physicalName() + ";";
        }

        @Override
        public List<String> commentRefresh(DdlContent.Table table, DdlContent.Column column) {
            if (column == null) {
                // 논리명이 없으면 DB에 남은 코멘트를 지운다(빈 코멘트 = 코멘트 없음, v1.36)
                return List.of("ALTER TABLE " + table.physicalName()
                        + (table.logicalName() == null ? " COMMENT=''" : tableOption(table)));
            }
            return List.of("ALTER TABLE " + table.physicalName() + " MODIFY COLUMN "
                    + DdlGenerator.columnAttributes(column, this) + " "
                    + (column.logicalName() == null ? "COMMENT ''" : columnComment(column)));
        }
    }

    /** IDENTITY 절 — PostgreSQL·Oracle. 자동 증가가 아니면 null */
    private static String identity(DdlContent.Column column) {
        if (!column.autoIncrement()) {
            return null;
        }
        return column.identityAlways() ? "GENERATED ALWAYS AS IDENTITY" : "GENERATED BY DEFAULT AS IDENTITY";
    }

    private static final class PostgresDialect extends BaseDialect {

        /** PostgreSQL 생성 컬럼은 STORED만 — 가상형은 STORED로 내고 생성기가 경고한다 */
        @Override
        protected String generatedStorage(DdlContent.Column column) {
            return "STORED";
        }

        private PostgresDialect() {
            super("postgres");
        }

        @Override
        protected Set<String> indexTypes() {
            return Set.of(DdlContent.Index.BTREE, DdlContent.Index.HASH, "GIN", "GIST", "BRIN", "SPGIST");
        }

        @Override
        protected boolean indexExpression() {
            return true;
        }

        @Override
        protected boolean indexWhere() {
            return true;
        }

        @Override
        protected boolean indexInclude() {
            return true;
        }

        @Override
        protected boolean indexOpclass() {
            return true;
        }

        @Override
        protected String indexMethodBeforeKeys(DdlContent.Index index) {
            return index.btree() ? "" : " USING " + index.type().toLowerCase(Locale.ROOT);
        }

        @Override
        public String autoIncrementInline(DdlContent.Column column) {
            // SERIAL 대신 IDENTITY — 시퀀스 객체 없이 컬럼 속성으로 실현된다 (PG 10+). 종류는 컬럼을 따른다(v1.37)
            return identity(column);
        }

        @Override
        public List<String> commentStatements(DdlContent.Table table) {
            return commentOnStatements(table);
        }

        @Override
        public String alterColumn(DdlContent.Table table, DdlContent.Column before, DdlContent.Column after) {
            // 절 조합 — 한 문장에 쉼표로 묶는다(SET TYPE / SET·DROP NOT NULL / SET·DROP DEFAULT)
            List<String> clauses = new ArrayList<>();
            String name = after.physicalName();
            if (!DdlGenerator.sameType(before, after)) {
                clauses.add("ALTER COLUMN " + name + " TYPE " + columnType(after));
            }
            if (before.nullable() != after.nullable()) {
                clauses.add("ALTER COLUMN " + name + (after.nullable() ? " DROP NOT NULL" : " SET NOT NULL"));
            }
            String afterDefault = DefaultLiterals.render(after, id());
            if (!DefaultLiterals.sameDefault(before, after)) {
                clauses.add(afterDefault == null
                        ? "ALTER COLUMN " + name + " DROP DEFAULT"
                        : "ALTER COLUMN " + name + " SET DEFAULT " + afterDefault);
            }
            if (before.autoIncrement() && after.autoIncrement() && before.identityAlways() != after.identityAlways()) {
                clauses.add("ALTER COLUMN " + name + " SET GENERATED " + (after.identityAlways() ? "ALWAYS" : "BY DEFAULT"));
            }
            if (clauses.isEmpty()) {
                // 반영 가능한 차이가 없다(예: AI만 변경) — 문장 없이 생성기 경고로 남긴다
                return "";
            }
            return "ALTER TABLE " + table.physicalName() + " " + String.join(", ", clauses) + ";";
        }

        @Override
        public List<String> commentRefresh(DdlContent.Table table, DdlContent.Column column) {
            // 논리명이 없으면 DB에 남은 코멘트를 지운다(IS NULL, v1.36)
            return column == null
                    ? List.of("COMMENT ON TABLE " + table.physicalName() + " IS " + commentLiteral(table.logicalName()))
                    : List.of("COMMENT ON COLUMN " + table.physicalName() + "." + column.physicalName()
                            + " IS " + commentLiteral(column.logicalName()));
        }
    }

    private static final class OracleDialect extends BaseDialect {

        private OracleDialect() {
            super("oracle");
        }

        /** 함수 기반 인덱스 */
        @Override
        protected boolean indexExpression() {
            return true;
        }

        /** Oracle 생성 컬럼은 VIRTUAL만 — 저장형은 VIRTUAL로 내고 생성기가 경고한다 */
        @Override
        protected String generatedStorage(DdlContent.Column column) {
            return "VIRTUAL";
        }

        @Override
        public String autoIncrementInline(DdlContent.Column column) {
            // 12c+ IDENTITY — 11g 시퀀스+트리거 방식은 후보
            return identity(column);
        }

        @Override
        public String addColumn(DdlContent.Table table, DdlContent.Column column) {
            // Oracle은 ADD 키워드 없이 괄호 묶음 — DEFAULT가 NOT NULL 앞에 온다(문법 다이어그램 순서)
            return "ALTER TABLE " + table.physicalName() + " ADD ("
                    + oracleColumnAttributes(column, this) + ");";
        }

        @Override
        public String alterColumn(DdlContent.Table table, DdlContent.Column before, DdlContent.Column after) {
            // MODIFY (전체 재정의) — DEFAULT → NOT NULL → IDENTITY 순서
            return "ALTER TABLE " + table.physicalName() + " MODIFY ("
                    + oracleColumnAttributes(after, this) + ");";
        }

        @Override
        public List<String> commentStatements(DdlContent.Table table) {
            return commentOnStatements(table);
        }
    }

    private static final class MssqlDialect extends BaseDialect {

        private MssqlDialect() {
            super("mssql");
        }

        /** 필터링된 인덱스 */
        @Override
        protected boolean indexWhere() {
            return true;
        }

        @Override
        protected boolean indexInclude() {
            return true;
        }

        @Override
        public String renameTable(String from, String to) {
            return "EXEC sp_rename '" + from + "', '" + to + "';";
        }

        @Override
        public String renameColumn(String table, String from, String to) {
            return "EXEC sp_rename '" + table + "." + from + "', '" + to + "', 'COLUMN';";
        }

        /** SQL Server 계산 컬럼 — 타입 없이 {@code AS (식) [PERSISTED]}. NOT NULL은 PERSISTED에서만 쓸 수 있다 */
        @Override
        public String generatedColumnDefinition(DdlContent.Column column) {
            StringBuilder definition = new StringBuilder(column.physicalName())
                    .append(" AS (").append(column.generated().expression()).append(")");
            if (column.generated().stored()) {
                definition.append(" PERSISTED");
                if (!column.nullable()) {
                    definition.append(" NOT NULL");
                }
            }
            return definition.toString();
        }

        @Override
        public String autoIncrementInline(DdlContent.Column column) {
            return column.autoIncrement() ? "IDENTITY(1,1)" : null;
        }

        @Override
        public String columnComment(DdlContent.Column column) {
            // 코멘트 메타데이터는 sp_addextendedproperty가 담당 — v1은 줄 주석으로 남긴다
            return column.logicalName() == null ? "" : "-- " + column.logicalName();
        }

        @Override
        public String createTablePrefix(DdlContent.Table table) {
            return lineCommentPrefix(table);
        }

        @Override
        public String addColumn(DdlContent.Table table, DdlContent.Column column) {
            // SQL Server는 COLUMN 키워드를 쓰지 않는다
            return "ALTER TABLE " + table.physicalName() + " ADD "
                    + DdlGenerator.columnAttributes(column, this) + ";";
        }

        @Override
        public String dropIndex(DdlContent.Table table, DdlContent.Index index) {
            return "DROP INDEX " + index.name() + " ON " + table.physicalName() + ";";
        }
    }

    /** 공용(논리) 폴백 — 미등록 DBMS 코드. 타입은 논리 코드 그대로 */
    private static final class CommonDialect extends BaseDialect {

        private CommonDialect() {
            super("common");
        }

        @Override
        public String columnComment(DdlContent.Column column) {
            return column.logicalName() == null ? "" : "-- " + column.logicalName();
        }

        @Override
        public String createTablePrefix(DdlContent.Table table) {
            return lineCommentPrefix(table);
        }
    }

    /* ---------- 방언 공용 헬퍼 ---------- */

    /** 컬럼 속성 뒤에 코멘트 조각 붙이기 — 코멘트 없으면 속성 그대로 */
    private static String withComment(String attributes, String comment) {
        return comment.isEmpty() ? attributes : attributes + " " + comment;
    }

    /** Oracle 컬럼 속성 — DEFAULT가 NOT NULL 앞에 오는 Oracle 문법 순서 */
    private static String oracleColumnAttributes(DdlContent.Column column, SqlDialect dialect) {
        if (column.generated() != null) {
            return dialect.generatedColumnDefinition(column);
        }
        StringBuilder attributes = new StringBuilder(column.physicalName())
                .append(' ').append(dialect.columnType(column));
        String defaultLiteral = DefaultLiterals.render(column, dialect.id());
        if (defaultLiteral != null) {
            attributes.append(" DEFAULT ").append(defaultLiteral);
        }
        if (!column.nullable()) {
            attributes.append(" NOT NULL");
        }
        String autoIncrement = dialect.autoIncrementInline(column);
        if (autoIncrement != null) {
            attributes.append(' ').append(autoIncrement);
        }
        return attributes.toString();
    }

    private static String commentLiteral(String logicalName) {
        return logicalName == null ? "NULL" : stringLiteral(logicalName);
    }

    /** COMMENT ON 방언(PG·Oracle) 공통 — 테이블·컬럼 코멘트(논리명)를 별도 문장으로 내보낸다 */
    private static List<String> commentOnStatements(DdlContent.Table table) {
        List<String> out = new ArrayList<>();
        if (table.logicalName() != null) {
            out.add("COMMENT ON TABLE " + table.physicalName() + " IS " + stringLiteral(table.logicalName()));
        }
        for (DdlContent.Column column : table.columns()) {
            if (column.logicalName() != null) {
                out.add("COMMENT ON COLUMN " + table.physicalName() + "." + column.physicalName()
                        + " IS " + stringLiteral(column.logicalName()));
            }
        }
        return out;
    }

    /** 줄 주석 방언(mssql·common) 공통 — 코멘트를 메타데이터가 아닌 주석으로 남긴다 */
    private static String lineCommentPrefix(DdlContent.Table table) {
        return table.logicalName() == null ? null : "-- " + table.logicalName();
    }

    /** SQL 문자열 리터럴 — 작은따옴표 이스케이프 */
    private static String stringLiteral(String value) {
        return "'" + value.replace("'", "''") + "'";
    }

    /** 인덱스 컬럼 목록 표기 — 존재하는 컬럼만, 연산자 클래스·컬럼별 정렬 포함(정렬은 BTREE만 받는다) */
    private static String indexColumns(DdlContent.Table table, DdlContent.Index index, boolean withOrder, boolean withOpclass) {
        List<String> parts = new ArrayList<>();
        for (DdlContent.IndexColumn indexColumn : index.columns()) {
            DdlContent.Column column = columnById(table, indexColumn.columnId());
            if (column != null) {
                StringBuilder part = new StringBuilder(column.physicalName());
                if (withOpclass && indexColumn.opclass() != null) {
                    part.append(' ').append(indexColumn.opclass());
                }
                if (withOrder) {
                    part.append(' ').append(indexColumn.order());
                }
                parts.add(part.toString());
            }
        }
        return String.join(", ", parts);
    }

    /** 컬럼 이름 하나(정렬 포함) — 식이 아닌 키 조각 */
    private static final java.util.regex.Pattern SIMPLE_KEY =
            java.util.regex.Pattern.compile("(?i)^[\\p{L}_][\\p{L}\\p{N}_$]*(\\s+(ASC|DESC))?$");

    /** 괄호·따옴표 밖의 쉼표로 나눈다 — 식 키 목록의 조각 */
    static List<String> splitTopLevel(String text) {
        List<String> parts = new ArrayList<>();
        int depth = 0;
        char quote = 0;
        int start = 0;
        for (int i = 0; i < text.length(); i++) {
            char ch = text.charAt(i);
            if (quote != 0) {
                if (ch == quote) {
                    quote = 0;
                }
            } else if (ch == '\'' || ch == '"' || ch == '`') {
                quote = ch;
            } else if (ch == '(') {
                depth++;
            } else if (ch == ')') {
                depth--;
            } else if (ch == ',' && depth == 0) {
                parts.add(text.substring(start, i));
                start = i + 1;
            }
        }
        parts.add(text.substring(start));
        return parts;
    }

    /** 컬럼 id → 컬럼 조회 — 없으면 null(삭제 cascade 잔여 참조 등) */
    private static DdlContent.Column columnById(DdlContent.Table table, String columnId) {
        for (DdlContent.Column column : table.columns()) {
            if (column.id() != null && column.id().equals(columnId)) {
                return column;
            }
        }
        return null;
    }
}
