package net.java21.crowfoot.api.model.ddl;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

/**
 * 방언 레지스트리 — 신규 DBMS는 여기에 구현을 추가한다.
 *
 * <p>자동 증가는 템플릿의 실현 방식과 무관하게 IDENTITY 계열로 통일한다
 * (MySQL AUTO_INCREMENT / MSSQL IDENTITY(1,1) / PG·Oracle GENERATED BY DEFAULT AS IDENTITY —
 * PG 10+·Oracle 12c+ 기준). Oracle 11g 시퀀스+트리거 방식은 후보로 남긴다.
 */
public final class Dialects {

    private Dialects() {
    }

    public static SqlDialect byId(String id) {
        SqlDialect dialect = REGISTRY.get(id);
        return dialect == null ? REGISTRY.get("common") : dialect;
    }

    private static final Map<String, SqlDialect> REGISTRY = Map.of(
            "mysql", new MysqlDialect(),
            "postgres", new PostgresDialect(),
            "oracle", new OracleDialect(),
            "mssql", new MssqlDialect(),
            "common", new CommonDialect());

    /* ---------- 공통 조립 — 모든 방언이 같은 규칙으로 시작하고 차이 지점만 덮어쓴다 ---------- */

    private abstract static class BaseDialect implements SqlDialect {

        private final String id;

        private BaseDialect(String id) {
            this.id = id;
        }

        @Override
        public final String id() {
            return id;
        }

        @Override
        public String columnType(DdlContent.Column column) {
            return DbmsTemplates.assembleType(column, id);
        }

        @Override
        public String autoIncrementInline(DdlContent.Column column) {
            return null;
        }

        @Override
        public String columnComment(DdlContent.Column column) {
            return "";
        }

        @Override
        public String createTablePrefix(DdlContent.Table table) {
            return null;
        }

        @Override
        public String tableOption(DdlContent.Table table) {
            return "";
        }

        @Override
        public List<String> commentStatements(DdlContent.Table table) {
            return List.of();
        }

        @Override
        public String createIndex(DdlContent.Table table, DdlContent.Index index) {
            return "CREATE INDEX " + index.name() + " ON " + table.physicalName()
                    + " (" + indexColumns(table, index) + ")";
        }

        /* ---------- 마이그레이션 ALTER — ANSI 기본형. 방언이 문법 차이만 덮어쓴다 ---------- */

        @Override
        public String addColumn(DdlContent.Table table, DdlContent.Column column) {
            return "ALTER TABLE " + table.physicalName() + " ADD COLUMN "
                    + DdlGenerator.columnAttributes(column, this) + ";";
        }

        @Override
        public String alterColumn(DdlContent.Table table, DdlContent.Column before, DdlContent.Column after) {
            // 기본형은 타입+NULL 허용 여부만 — 기본값 변경은 방언마다 문법이 갈라져 각자 덮어쓴다
            StringBuilder statement = new StringBuilder("ALTER TABLE ").append(table.physicalName())
                    .append(" ALTER COLUMN ").append(after.physicalName())
                    .append(' ').append(columnType(after));
            if (!after.nullable()) {
                statement.append(" NOT NULL");
            }
            return statement.append(";").toString();
        }

        @Override
        public String dropColumn(DdlContent.Table table, DdlContent.Column column) {
            return "ALTER TABLE " + table.physicalName() + " DROP COLUMN " + column.physicalName() + ";";
        }

        @Override
        public String dropConstraint(DdlContent.Table table, String name, String kind) {
            return "ALTER TABLE " + table.physicalName() + " DROP CONSTRAINT " + name + ";";
        }

        @Override
        public String dropIndex(DdlContent.Table table, DdlContent.Index index) {
            return "DROP INDEX " + index.name() + ";";
        }

        @Override
        public List<String> commentRefresh(DdlContent.Table table, DdlContent.Column column) {
            // 코멘트가 줄 주석으로만 존재하는 방언은 CREATE 본문 외에 갱신할 곳이 없다
            return List.of();
        }
    }

    /* ---------- 방언별 차이 지점 ---------- */

    private static final class MysqlDialect extends BaseDialect {

        private MysqlDialect() {
            super("mysql");
        }

        @Override
        public String autoIncrementInline(DdlContent.Column column) {
            return column.autoIncrement() ? "AUTO_INCREMENT" : null;
        }

        @Override
        public String columnComment(DdlContent.Column column) {
            return column.logicalName() == null ? "" : "COMMENT " + stringLiteral(column.logicalName());
        }

        @Override
        public String tableOption(DdlContent.Table table) {
            return table.logicalName() == null ? "" : " COMMENT=" + stringLiteral(table.logicalName());
        }

        @Override
        public String addColumn(DdlContent.Table table, DdlContent.Column column) {
            // 코멘트는 컬럼 정의에 인라인 — 추가 시점에 함께 심는다
            return "ALTER TABLE " + table.physicalName() + " ADD COLUMN "
                    + withComment(DdlGenerator.columnAttributes(column, this), columnComment(column)) + ";";
        }

        @Override
        public String alterColumn(DdlContent.Table table, DdlContent.Column before, DdlContent.Column after) {
            // MODIFY는 전체 재정의다 — 생략한 속성·코멘트가 사라지므로 after 정의를 전부 다시 쓴다
            return "ALTER TABLE " + table.physicalName() + " MODIFY COLUMN "
                    + withComment(DdlGenerator.columnAttributes(after, this), columnComment(after)) + ";";
        }

        @Override
        public String dropConstraint(DdlContent.Table table, String name, String kind) {
            // UK는 인덱스로, PK는 이름 없는 상수 제약으로 실현된다 — 이름 문법이 각자 다르다
            String target = switch (kind == null ? "" : kind) {
                case KIND_PRIMARY -> "PRIMARY KEY";
                case KIND_UNIQUE -> "INDEX " + name;
                case KIND_FOREIGN_KEY -> "FOREIGN KEY " + name;
                default -> "CONSTRAINT " + name;
            };
            return "ALTER TABLE " + table.physicalName() + " DROP " + target + ";";
        }

        @Override
        public String dropIndex(DdlContent.Table table, DdlContent.Index index) {
            return "DROP INDEX " + index.name() + " ON " + table.physicalName() + ";";
        }

        @Override
        public List<String> commentRefresh(DdlContent.Table table, DdlContent.Column column) {
            if (column == null) {
                return table.logicalName() == null || tableOption(table).isEmpty() ? List.of()
                        : List.of("ALTER TABLE " + table.physicalName() + tableOption(table));
            }
            // 코멘트 해제는 MODIFY로 표현할 수 없다 — 논리명이 있을 때만 갱신한다
            if (column.logicalName() == null) {
                return List.of();
            }
            return List.of("ALTER TABLE " + table.physicalName() + " MODIFY COLUMN "
                    + DdlGenerator.columnAttributes(column, this) + " " + columnComment(column));
        }
    }

    private static final class PostgresDialect extends BaseDialect {

        private PostgresDialect() {
            super("postgres");
        }

        @Override
        public String autoIncrementInline(DdlContent.Column column) {
            // SERIAL 대신 IDENTITY — 시퀀스 객체 없이 컬럼 속성으로 실현된다 (PG 10+)
            return column.autoIncrement() ? "GENERATED BY DEFAULT AS IDENTITY" : null;
        }

        @Override
        public List<String> commentStatements(DdlContent.Table table) {
            return commentOnStatements(table);
        }

        @Override
        public String alterColumn(DdlContent.Table table, DdlContent.Column before, DdlContent.Column after) {
            // 절 조합 — 한 문장에 쉼표로 묶는다(SET TYPE / SET·DROP NOT NULL / SET·DROP DEFAULT)
            List<String> clauses = new ArrayList<>();
            String name = after.physicalName();
            if (!DdlGenerator.sameType(before, after)) {
                clauses.add("ALTER COLUMN " + name + " TYPE " + columnType(after));
            }
            if (before.nullable() != after.nullable()) {
                clauses.add("ALTER COLUMN " + name + (after.nullable() ? " DROP NOT NULL" : " SET NOT NULL"));
            }
            String beforeDefault = DdlGenerator.normalizedDefault(before);
            String afterDefault = DdlGenerator.normalizedDefault(after);
            if (!java.util.Objects.equals(beforeDefault, afterDefault)) {
                clauses.add(afterDefault == null
                        ? "ALTER COLUMN " + name + " DROP DEFAULT"
                        : "ALTER COLUMN " + name + " SET DEFAULT " + afterDefault);
            }
            if (clauses.isEmpty()) {
                // 반영 가능한 차이가 없다(예: AI만 변경) — 문장 없이 생성기 경고로 남긴다
                return "";
            }
            return "ALTER TABLE " + table.physicalName() + " " + String.join(", ", clauses) + ";";
        }

        @Override
        public List<String> commentRefresh(DdlContent.Table table, DdlContent.Column column) {
            return column == null
                    ? (table.logicalName() == null ? List.of() : List.of("COMMENT ON TABLE "
                            + table.physicalName() + " IS " + stringLiteral(table.logicalName())))
                    : (column.logicalName() == null ? List.of() : List.of("COMMENT ON COLUMN "
                            + table.physicalName() + "." + column.physicalName()
                            + " IS " + stringLiteral(column.logicalName())));
        }
    }

    private static final class OracleDialect extends BaseDialect {

        private OracleDialect() {
            super("oracle");
        }

        @Override
        public String autoIncrementInline(DdlContent.Column column) {
            // 12c+ IDENTITY — 11g 시퀀스+트리거 방식은 후보
            return column.autoIncrement() ? "GENERATED BY DEFAULT AS IDENTITY" : null;
        }

        @Override
        public String addColumn(DdlContent.Table table, DdlContent.Column column) {
            // Oracle은 ADD 키워드 없이 괄호 묶음 — DEFAULT가 NOT NULL 앞에 온다(문법 다이어그램 순서)
            return "ALTER TABLE " + table.physicalName() + " ADD ("
                    + oracleColumnAttributes(column, this) + ");";
        }

        @Override
        public String alterColumn(DdlContent.Table table, DdlContent.Column before, DdlContent.Column after) {
            // MODIFY (전체 재정의) — DEFAULT → NOT NULL → IDENTITY 순서
            return "ALTER TABLE " + table.physicalName() + " MODIFY ("
                    + oracleColumnAttributes(after, this) + ");";
        }

        @Override
        public List<String> commentStatements(DdlContent.Table table) {
            return commentOnStatements(table);
        }
    }

    private static final class MssqlDialect extends BaseDialect {

        private MssqlDialect() {
            super("mssql");
        }

        @Override
        public String autoIncrementInline(DdlContent.Column column) {
            return column.autoIncrement() ? "IDENTITY(1,1)" : null;
        }

        @Override
        public String columnComment(DdlContent.Column column) {
            // 코멘트 메타데이터는 sp_addextendedproperty가 담당 — v1은 줄 주석으로 남긴다
            return column.logicalName() == null ? "" : "-- " + column.logicalName();
        }

        @Override
        public String createTablePrefix(DdlContent.Table table) {
            return lineCommentPrefix(table);
        }

        @Override
        public String addColumn(DdlContent.Table table, DdlContent.Column column) {
            // SQL Server는 COLUMN 키워드를 쓰지 않는다
            return "ALTER TABLE " + table.physicalName() + " ADD "
                    + DdlGenerator.columnAttributes(column, this) + ";";
        }

        @Override
        public String dropIndex(DdlContent.Table table, DdlContent.Index index) {
            return "DROP INDEX " + index.name() + " ON " + table.physicalName() + ";";
        }
    }

    /** 공용(논리) 폴백 — 미등록 DBMS 코드. 타입은 논리 코드 그대로 */
    private static final class CommonDialect extends BaseDialect {

        private CommonDialect() {
            super("common");
        }

        @Override
        public String columnComment(DdlContent.Column column) {
            return column.logicalName() == null ? "" : "-- " + column.logicalName();
        }

        @Override
        public String createTablePrefix(DdlContent.Table table) {
            return lineCommentPrefix(table);
        }
    }

    /* ---------- 방언 공용 헬퍼 ---------- */

    /** 컬럼 속성 뒤에 코멘트 조각 붙이기 — 코멘트 없으면 속성 그대로 */
    private static String withComment(String attributes, String comment) {
        return comment.isEmpty() ? attributes : attributes + " " + comment;
    }

    /** Oracle 컬럼 속성 — DEFAULT가 NOT NULL 앞에 오는 Oracle 문법 순서 */
    private static String oracleColumnAttributes(DdlContent.Column column, SqlDialect dialect) {
        StringBuilder attributes = new StringBuilder(column.physicalName())
                .append(' ').append(dialect.columnType(column));
        if (column.defaultValue() != null) {
            attributes.append(" DEFAULT ").append(column.defaultValue());
        }
        if (!column.nullable()) {
            attributes.append(" NOT NULL");
        }
        String autoIncrement = dialect.autoIncrementInline(column);
        if (autoIncrement != null) {
            attributes.append(' ').append(autoIncrement);
        }
        return attributes.toString();
    }

    /** COMMENT ON 방언(PG·Oracle) 공통 — 테이블·컬럼 코멘트(논리명)를 별도 문장으로 내보낸다 */
    private static List<String> commentOnStatements(DdlContent.Table table) {
        List<String> out = new ArrayList<>();
        if (table.logicalName() != null) {
            out.add("COMMENT ON TABLE " + table.physicalName() + " IS " + stringLiteral(table.logicalName()));
        }
        for (DdlContent.Column column : table.columns()) {
            if (column.logicalName() != null) {
                out.add("COMMENT ON COLUMN " + table.physicalName() + "." + column.physicalName()
                        + " IS " + stringLiteral(column.logicalName()));
            }
        }
        return out;
    }

    /** 줄 주석 방언(mssql·common) 공통 — 코멘트를 메타데이터가 아닌 주석으로 남긴다 */
    private static String lineCommentPrefix(DdlContent.Table table) {
        return table.logicalName() == null ? null : "-- " + table.logicalName();
    }

    /** SQL 문자열 리터럴 — 작은따옴표 이스케이프 */
    private static String stringLiteral(String value) {
        return "'" + value.replace("'", "''") + "'";
    }

    /** 인덱스 컬럼 목록 표기 — 존재하는 컬럼만, 컬럼별 정렬 포함 */
    private static String indexColumns(DdlContent.Table table, DdlContent.Index index) {
        List<String> parts = new ArrayList<>();
        for (DdlContent.IndexColumn indexColumn : index.columns()) {
            DdlContent.Column column = columnById(table, indexColumn.columnId());
            if (column != null) {
                parts.add(column.physicalName() + " " + indexColumn.order());
            }
        }
        return String.join(", ", parts);
    }

    /** 컬럼 id → 컬럼 조회 — 없으면 null(삭제 cascade 잔여 참조 등) */
    private static DdlContent.Column columnById(DdlContent.Table table, String columnId) {
        for (DdlContent.Column column : table.columns()) {
            if (column.id() != null && column.id().equals(columnId)) {
                return column;
            }
        }
        return null;
    }
}
