package net.java21.crowfoot.api.model.ddl;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

/**
 * 방언 레지스트리 — 신규 DBMS는 여기에 구현을 추가한다.
 *
 * <p>자동 증가는 템플릿의 실현 방식과 무관하게 IDENTITY 계열로 통일한다
 * (MySQL AUTO_INCREMENT / MSSQL IDENTITY(1,1) / PG·Oracle GENERATED BY DEFAULT AS IDENTITY —
 * PG 10+·Oracle 12c+ 기준). Oracle 11g 시퀀스+트리거 방식은 후보로 남긴다.
 */
public final class Dialects {

    private Dialects() {
    }

    public static SqlDialect byId(String id) {
        SqlDialect dialect = REGISTRY.get(id);
        return dialect == null ? REGISTRY.get("common") : dialect;
    }

    private static final Map<String, SqlDialect> REGISTRY = Map.of(
            "mysql", new MysqlDialect(),
            "postgres", new PostgresDialect(),
            "oracle", new OracleDialect(),
            "mssql", new MssqlDialect(),
            "common", new CommonDialect());

    /* ---------- 공통 조립 — 모든 방언이 같은 규칙으로 시작하고 차이 지점만 덮어쓴다 ---------- */

    private abstract static class BaseDialect implements SqlDialect {

        private final String id;

        private BaseDialect(String id) {
            this.id = id;
        }

        @Override
        public final String id() {
            return id;
        }

        @Override
        public String columnType(DdlContent.Column column) {
            return DbmsTemplates.assembleType(column, id);
        }

        @Override
        public String autoIncrementInline(DdlContent.Column column) {
            return null;
        }

        @Override
        public String columnComment(DdlContent.Column column) {
            return "";
        }

        @Override
        public String createTablePrefix(DdlContent.Table table) {
            return null;
        }

        @Override
        public String tableOption(DdlContent.Table table) {
            return "";
        }

        @Override
        public List<String> commentStatements(DdlContent.Table table) {
            return List.of();
        }

        @Override
        public String createIndex(DdlContent.Table table, DdlContent.Index index) {
            return "CREATE INDEX " + index.name() + " ON " + table.physicalName()
                    + " (" + indexColumns(table, index) + ")";
        }
    }

    /* ---------- 방언별 차이 지점 ---------- */

    private static final class MysqlDialect extends BaseDialect {

        private MysqlDialect() {
            super("mysql");
        }

        @Override
        public String autoIncrementInline(DdlContent.Column column) {
            return column.autoIncrement() ? "AUTO_INCREMENT" : null;
        }

        @Override
        public String columnComment(DdlContent.Column column) {
            return column.logicalName() == null ? "" : "COMMENT " + stringLiteral(column.logicalName());
        }

        @Override
        public String tableOption(DdlContent.Table table) {
            return table.logicalName() == null ? "" : " COMMENT=" + stringLiteral(table.logicalName());
        }
    }

    private static final class PostgresDialect extends BaseDialect {

        private PostgresDialect() {
            super("postgres");
        }

        @Override
        public String autoIncrementInline(DdlContent.Column column) {
            // SERIAL 대신 IDENTITY — 시퀀스 객체 없이 컬럼 속성으로 실현된다 (PG 10+)
            return column.autoIncrement() ? "GENERATED BY DEFAULT AS IDENTITY" : null;
        }

        @Override
        public List<String> commentStatements(DdlContent.Table table) {
            return commentOnStatements(table);
        }
    }

    private static final class OracleDialect extends BaseDialect {

        private OracleDialect() {
            super("oracle");
        }

        @Override
        public String autoIncrementInline(DdlContent.Column column) {
            // 12c+ IDENTITY — 11g 시퀀스+트리거 방식은 후보
            return column.autoIncrement() ? "GENERATED BY DEFAULT AS IDENTITY" : null;
        }

        @Override
        public List<String> commentStatements(DdlContent.Table table) {
            return commentOnStatements(table);
        }
    }

    private static final class MssqlDialect extends BaseDialect {

        private MssqlDialect() {
            super("mssql");
        }

        @Override
        public String autoIncrementInline(DdlContent.Column column) {
            return column.autoIncrement() ? "IDENTITY(1,1)" : null;
        }

        @Override
        public String columnComment(DdlContent.Column column) {
            // 코멘트 메타데이터는 sp_addextendedproperty가 담당 — v1은 줄 주석으로 남긴다
            return column.logicalName() == null ? "" : "-- " + column.logicalName();
        }

        @Override
        public String createTablePrefix(DdlContent.Table table) {
            return lineCommentPrefix(table);
        }
    }

    /** 공용(논리) 폴백 — 미등록 DBMS 코드. 타입은 논리 코드 그대로 */
    private static final class CommonDialect extends BaseDialect {

        private CommonDialect() {
            super("common");
        }

        @Override
        public String columnComment(DdlContent.Column column) {
            return column.logicalName() == null ? "" : "-- " + column.logicalName();
        }

        @Override
        public String createTablePrefix(DdlContent.Table table) {
            return lineCommentPrefix(table);
        }
    }

    /* ---------- 방언 공용 헬퍼 ---------- */

    /** COMMENT ON 방언(PG·Oracle) 공통 — 테이블·컬럼 코멘트(논리명)를 별도 문장으로 내보낸다 */
    private static List<String> commentOnStatements(DdlContent.Table table) {
        List<String> out = new ArrayList<>();
        if (table.logicalName() != null) {
            out.add("COMMENT ON TABLE " + table.physicalName() + " IS " + stringLiteral(table.logicalName()));
        }
        for (DdlContent.Column column : table.columns()) {
            if (column.logicalName() != null) {
                out.add("COMMENT ON COLUMN " + table.physicalName() + "." + column.physicalName()
                        + " IS " + stringLiteral(column.logicalName()));
            }
        }
        return out;
    }

    /** 줄 주석 방언(mssql·common) 공통 — 코멘트를 메타데이터가 아닌 주석으로 남긴다 */
    private static String lineCommentPrefix(DdlContent.Table table) {
        return table.logicalName() == null ? null : "-- " + table.logicalName();
    }

    /** SQL 문자열 리터럴 — 작은따옴표 이스케이프 */
    private static String stringLiteral(String value) {
        return "'" + value.replace("'", "''") + "'";
    }

    /** 인덱스 컬럼 목록 표기 — 존재하는 컬럼만, 컬럼별 정렬 포함 */
    private static String indexColumns(DdlContent.Table table, DdlContent.Index index) {
        List<String> parts = new ArrayList<>();
        for (DdlContent.IndexColumn indexColumn : index.columns()) {
            DdlContent.Column column = columnById(table, indexColumn.columnId());
            if (column != null) {
                parts.add(column.physicalName() + " " + indexColumn.order());
            }
        }
        return String.join(", ", parts);
    }

    /** 컬럼 id → 컬럼 조회 — 없으면 null(삭제 cascade 잔여 참조 등) */
    private static DdlContent.Column columnById(DdlContent.Table table, String columnId) {
        for (DdlContent.Column column : table.columns()) {
            if (column.id() != null && column.id().equals(columnId)) {
                return column;
            }
        }
        return null;
    }
}
